
name: Messaging app CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DJANGO_SECRET_KEY: 69tgugtg%^fgJO&*&
  MYSQL_DB: mydb
  MYSQL_USER: userdb
  MYSQL_PASSWORD: password
  MYSQL_DB_HOST: localhost
  MYSQL_DB_PORT: 3306
  DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,[::1],*
  DJANGO_DEBUG: False
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12.3]
    services:
      mysql:
        image: mysql
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root --password=secret --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DB }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd messaging_app
        python3 -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: |
        cd messaging_app
        source venv/bin/activate
        python manage.py makemigrations
        python manage.py migrate
    - name: Run Tests and generate report
      run: |
        cd messaging_app
        source venv/bin/activate
        pytest --junitxml=junit/test-results.xml --cov= --cov-report=xml --cov-report=html
    - name: Publish test coverage report
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: junit/test-results.html
    - name: Run Code Quality Checks(Static Code Analysis) with flake8
      run: |
        cd messaging_app
        source venv/bin/activate
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
