
pipeline {
    agent any
    stages {
        stage("Pull code from GitHub") {
            steps {
                git branch: 'main',
                    credentialsId: 'GitHub_Cred',
                    url: 'https://github.com/realdkd001/alx-backend-python'
            }
        }
        stage("install dependencies") {
            steps {
                dir('messaging_app') {
                    sh '''
                        rm -rf venv
                        python3 -m venv venv
                        bash -c "source venv/bin/activate"
                        venv/bin/pip3 install --upgrade pip
                        bash -c "apt install python3-dev default-libmysqlclient-dev build-essential pkg-config -y"
                        venv/bin/pip3 install -r messaging_app/requirements.txt
                    '''
                }
            }
        }
        stage("Test") {
            steps {
                dir("messaging_app") {
                    sh '''
                        bash -c "source venv/bin/activate"
                        venv/bin/pytest
                    '''
                }
            }
        }
        stage("Build image") {
            steps {
                dir("messaging_app/messaging_app") {
                    script {
                        docker.build("realdkd001/message_app:${env.BUILD_NUMBER}")
                    }
                }
            }
        }
        stage("Push image to dockerhub") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub_cred', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
                    sh "echo ${PASSWORD} | docker login -u ${USERNAME} --password-stdin"
                    sh "docker push realdkd001/message_app:${env.BUILD_NUMBER}"
                }
            }
        }        
    }
    
    post {
        always {
            dir("messaging_app") {
                sh '''
                    bash -c "source venv/bin/activate"
                    venv/bin/pytest --cov
                '''
            }
        }
    }
}
